name: To-Do App CI/CD Pipeline

on:
    push:
        branches:
            - feature/test-phase1

jobs:
    Build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5.0.0

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3.11.1
              with: 
                install: true
                driver-opts: |
                    image=moby/buildkit:rootless
            
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                push: true
                context: .
                file: ./Dockerfile
                tags: zinlinhtetdevops/todo-app:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Login to AWS Lightsail
            uses: appleboy/ssh-action@v1.2.2
            with:
              host: ${{ secrets.LIGHTSAIL_HOST}}
              username: ${{ secrets.LIGHTSAIL_USER }}
              key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
              port: 22
              script: |
                echo "Pulling Docker Latest Image ..."
                sudo docker pull zinlinhtetdevops/todo-app:latest

                echo "Stopping old container ..."
                sudo docker ps 
                sudo docker stop demo || true
                sudo docker rm demo || true  

                echo "Starting new container ..."
                sudo docker run -itd -p 3000:3000 -e MONGODB_URI="${{ secrets.MONGODB_URI}}" --name demo zinlinhtetdevops/todo-app:latest
