name: To-Do App CI/CD Pipeline

on:
    push:
        branches:
            - feature/test-phase1

jobs:
    Build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5.0.0

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3.11.1
              with: 
                install: true
                driver-opts: |
                    image=moby/buildkit:rootless
            
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                push: true
                context: .
                file: ./Dockerfile
                tags: zinlinhtetdevops/todo-app:latest

